version: '3.8'

services:
  web:
    container_name: web
    build: .
    restart: unless-stopped

    networks:
      - db_network

    environment:
      - DEBUG=0
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    ports:
      - "8080:8080"

    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped

    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=storage

    env_file:
      - .env

    networks:
      - db_network

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:latest

    networks:
      - db_network

    ports:
      - "6379:6379"

networks:
  db_network:
    driver: bridge

volumes:
  db_data:
